/* BellyUp demo — voluntary surplus reports in, agency→hotspot dispatch out.
   Data comes from data.js (generated by scripts/build_demo_data.py). */

"use strict";

const C = CONSTANTS;
const CANDIDATES = HOTSPOTS.filter(h => h.need >= C.MIN_CANDIDATE_NEED);
const REPORTING = SUPPLIERS.filter(s => s.report);

/* ---------------------------------------------------------------- helpers */
const $ = id => document.getElementById(id);
const fmt$ = v => (v < 0 ? "-$" : "$") + Math.abs(v).toFixed(2);
const fmtInt = v => Math.round(v).toLocaleString();
const agShort = a => a.name
  .replace("Jacobs & Cushman San Diego Food Bank", "SD Food Bank")
  .replace("Catholic Charities Diocese of San Diego", "Catholic Charities");

function haversineMi(a, b) {
  const R = 3958.76, rad = Math.PI / 180;
  const dLat = (b.lat - a.lat) * rad, dLon = (b.lon - a.lon) * rad;
  const s = Math.sin(dLat / 2) ** 2 +
    Math.cos(a.lat * rad) * Math.cos(b.lat * rad) * Math.sin(dLon / 2) ** 2;
  return 2 * R * Math.asin(Math.sqrt(s));
}
const roadMi = (a, b) => haversineMi(a, b) * C.ROAD_FACTOR;

/* ------------------------------------------------------- matching engine */
/* Input: one supplier report. Output: ranked (agency, hotspot) pairs.
   net = reward − cost
   reward = mealsServed × MEAL_VALUE × accessBoost + surplusMeals × MEAL_VALUE × 0.5
     mealsServed  = min(meals reported, block need)  — one meal per person tonight
     accessBoost  = 1 + ACCESS_BOOST_MAX × (7 − food-access days/wk)/7
     surplus      = meals beyond block need, absorbed by agency pantry network
   cost = labor + mileage over HQ → pickup → hotspot
     labor    = (drive minutes + handling) × $17.75/hr
     mileage  = road miles × $0.76/mi                                        */
function computeDispatch(supplier) {
  const meals = supplier.report.lbs / C.LBS_PER_MEAL;
  const prepared = supplier.surplus === "prepared";
  const eligible = AGENCIES.filter(a => !prepared || a.acceptsPrepared);
  const pairs = [];

  for (const a of eligible) {
    const leg1 = roadMi(a, supplier);
    for (const h of CANDIDATES) {
      const leg2 = roadMi(supplier, h);
      const miles = leg1 + leg2;
      const driveMin = miles / C.AVG_SPEED_MPH * 60;
      const minutes = driveMin + C.HANDLING_MIN;
      const labor = minutes / 60 * C.WAGE_PER_HR;
      const mileage = miles * C.COST_PER_MILE;

      const served = Math.min(meals, h.need);
      const surplus = meals - served;
      const boost = 1 + C.ACCESS_BOOST_MAX * (7 - Math.min(h.accessDays, 7)) / 7;
      const reward = served * C.MEAL_VALUE * boost + surplus * C.MEAL_VALUE * 0.5;

      pairs.push({
        agency: a, hotspot: h,
        leg1, leg2, miles, driveMin, minutes, labor, mileage,
        cost: labor + mileage,
        served, surplus, boost, reward,
        net: reward - (labor + mileage),
      });
    }
  }
  pairs.sort((p, q) => q.net - p.net);
  return { meals, prepared, eligible, pairs, evaluated: pairs.length };
}

/* ------------------------------------------------------------------- map */
const map = L.map("map", { zoomControl: true, attributionControl: true });
L.tileLayer("https://{s}.basemaps.cartocdn.com/dark_all/{z}/{x}/{y}{r}.png", {
  attribution: '&copy; <a href="https://www.openstreetmap.org/copyright">OSM</a> &copy; <a href="https://carto.com/">CARTO</a>',
  maxZoom: 19,
}).addTo(map);

const downtown = L.latLngBounds(HOTSPOTS.map(h => [h.lat, h.lon]));
map.fitBounds(downtown.pad(0.12));

const fxLayer = L.layerGroup().addTo(map);   // scan lines, routes, radar

/* hotspot circles — magenta, sized by need */
const hotspotMarkers = {};
for (const h of HOTSPOTS) {
  const m = L.circleMarker([h.lat, h.lon], {
    radius: 3 + Math.sqrt(h.need) * 2.1,
    color: "#d55181",
    weight: 1.4,
    opacity: 0.8,
    fillColor: "#d55181",
    fillOpacity: 0.16 + Math.min(h.need / 40, 0.34),
    className: "hs-path",
  }).addTo(map);
  m.bindTooltip(
    `<b>${h.location}</b> &middot; ${h.area}` +
    `<div class="tip-k">need ${h.need.toFixed(1)} person-equivalents &middot; rank #${h.rank}` +
    `<br>food access ${h.accessDays.toFixed(h.accessDays % 1 ? 1 : 0)} days/week</div>`,
    { className: "hs-tip", direction: "top", opacity: 1 }
  );
  hotspotMarkers[h.id] = m;
}

/* agency HQ markers */
const TRUCK_SVG = '<svg viewBox="0 0 24 24" fill="currentColor"><path d="M3 5h11v9H3zM14 8h4l3 3v3h-7zM6 18a2 2 0 1 0 0-4 2 2 0 0 0 0 4zm11 0a2 2 0 1 0 0-4 2 2 0 0 0 0 4z"/></svg>';
const agencyMarkers = {};
for (const a of AGENCIES) {
  const m = L.marker([a.lat, a.lon], {
    icon: L.divIcon({ className: "", html: `<div class="mk-agency" id="ag-${a.id}">${TRUCK_SVG}</div>`, iconSize: [26, 26], iconAnchor: [13, 13] }),
    zIndexOffset: 500,
  }).addTo(map);
  m.bindTooltip(
    `<b>${a.name}</b><div class="tip-k">${a.program}` +
    `<br>${a.acceptsPrepared ? "accepts prepared food" : "packaged/produce"}</div>`,
    { className: "hs-tip", direction: "top", opacity: 1 }
  );
  agencyMarkers[a.id] = m;
}

/* supplier markers — the "input markers", always on the map */
const supplierMarkers = {};
for (const s of SUPPLIERS) {
  const cls = s.report ? "mk-supplier" : "mk-supplier quiet";
  const m = L.marker([s.lat, s.lon], {
    icon: L.divIcon({ className: "", html: `<div class="${cls}" id="sp-${s.id}"></div>`, iconSize: [14, 14], iconAnchor: [7, 7] }),
    zIndexOffset: 700,
  }).addTo(map);
  const rep = s.report
    ? `<br><b style="color:#eb6834">${s.report.lbs} lbs</b> ${s.surplus} &middot; reported ${s.report.time}`
    : "<br>no surplus reported tonight";
  m.bindTooltip(
    `<b>${s.name}</b><div class="tip-k">${s.type}${rep}</div>`,
    { className: "hs-tip", direction: "top", opacity: 1 }
  );
  if (s.report) m.on("click", () => selectReport(s));
  supplierMarkers[s.id] = m;
}

/* ------------------------------------------------------------------ feed */
const typeIcon = { grocery: "🛒", hotel: "🏨", venue: "🏟", health: "🏥" };
$("feed").innerHTML = REPORTING.map(s => `
  <div class="report-card" id="card-${s.id}">
    <div class="rc-top">
      <span>${typeIcon[s.type] || "🍽"}</span>
      <span class="rc-name">${s.name}</span>
      <span class="rc-time">${s.report.time}</span>
    </div>
    <div class="rc-mid">
      <span class="rc-lbs">${s.report.lbs} lbs</span>
      <span class="rc-meals">&asymp; ${fmtInt(s.report.lbs / C.LBS_PER_MEAL)} meals</span>
      <span class="rc-chip ${s.surplus === "prepared" ? "prepared" : ""}">${s.surplus}</span>
    </div>
    <div class="rc-items">${s.report.items}</div>
  </div>`).join("");
for (const s of REPORTING) $("card-" + s.id).addEventListener("click", () => selectReport(s));

/* --------------------------------------------------------------- topbar */
const totLbs = REPORTING.reduce((t, s) => t + s.report.lbs, 0);
$("topstats").innerHTML = [
  [fmtInt(totLbs) + " lbs", "reported tonight"],
  ["~" + fmtInt(totLbs / C.LBS_PER_MEAL), "potential meals"],
  [REPORTING.length, "active reports"],
  [CANDIDATES.length, "blocks in need"],
].map(([v, k]) => `<div class="stat-chip"><div class="v">${v}</div><div class="k">${k}</div></div>`).join("");
$("topdate").textContent = new Date().toLocaleDateString("en-US",
  { weekday: "short", month: "short", day: "numeric", year: "numeric" });

/* ------------------------------------------------- selection + animation */
let animToken = 0;
let selectedId = null;

function clearFx() {
  fxLayer.clearLayers();
  $("calcOverlay").classList.remove("show");
  document.querySelectorAll(".mk-agency.winner").forEach(el => el.classList.remove("winner"));
  document.querySelectorAll(".mk-supplier.selected").forEach(el => el.classList.remove("selected"));
  for (const id in hotspotMarkers) {
    const el = hotspotMarkers[id].getElement();
    if (el) el.classList.remove("hs-winner", "hs-scanned");
  }
}

function selectReport(s) {
  if (selectedId === s.id) return;
  selectedId = s.id;
  const token = ++animToken;
  clearFx();

  document.querySelectorAll(".report-card.active").forEach(el => el.classList.remove("active"));
  const card = $("card-" + s.id);
  card.classList.add("active");
  card.scrollIntoView({ block: "nearest", behavior: "smooth" });
  $("sp-" + s.id).classList.add("selected");

  const result = computeDispatch(s);
  runTriangulation(s, result, token);
}

function runTriangulation(s, result, token) {
  const best = result.pairs[0];
  const live = () => token === animToken;

  /* hide any previous result while we "compute" */
  $("resultBody").hidden = true;
  $("resultEmpty").style.display = "none";

  const scanBounds = L.latLngBounds(HOTSPOTS.map(h => [h.lat, h.lon])).extend([s.lat, s.lon]);
  map.flyToBounds(scanBounds.pad(0.1), { duration: 0.55 });

  /* radar pulse at the supplier */
  fxLayer.addLayer(L.marker([s.lat, s.lon], {
    icon: L.divIcon({ className: "", html: '<div class="radar"><span></span><span></span><span></span></div>', iconSize: [12, 12], iconAnchor: [6, 6] }),
    interactive: false, zIndexOffset: 900,
  }));

  /* calc overlay */
  const constraint = result.prepared
    ? `constraint: prepared food &rarr; ${result.eligible.length} of ${AGENCIES.length} agencies eligible`
    : `${result.eligible.length} agencies &times; ${CANDIDATES.length} blocks`;
  $("calcTitle").textContent = "TRIANGULATING";
  $("calcLine").innerHTML = `${s.name} &middot; ${constraint}`;
  $("calcOverlay").classList.add("show");

  const SCAN_MS = 1350, SHORTLIST_MS = 850;

  /* pair counter counts up through the scan */
  const t0 = performance.now();
  (function tick(now) {
    if (!live()) return;
    const p = Math.min((now - t0) / SCAN_MS, 1);
    $("calcCount").textContent = fmtInt(result.evaluated * (1 - Math.pow(1 - p, 3)));
    if (p < 1) requestAnimationFrame(tick);
  })(t0);

  /* scan lines: quick flicks from the supplier to sampled candidate blocks */
  const sample = [...CANDIDATES].sort(() => Math.random() - 0.5).slice(0, 26);
  sample.forEach((h, i) => {
    setTimeout(() => {
      if (!live()) return;
      const line = L.polyline([[s.lat, s.lon], [h.lat, h.lon]], {
        color: "#eb6834", weight: 1.3, opacity: 0.9, className: "scan-line", interactive: false,
      });
      fxLayer.addLayer(line);
      setTimeout(() => fxLayer.removeLayer(line), 520);
      const el = hotspotMarkers[h.id].getElement();
      if (el) { el.classList.remove("hs-scanned"); void el.getBBox; el.classList.add("hs-scanned"); }
    }, 90 + i * (SCAN_MS - 200) / sample.length);
  });

  /* shortlist: top-3 hotspots pulse while agencies are weighed */
  setTimeout(() => {
    if (!live()) return;
    $("calcTitle").textContent = "SHORTLISTING";
    $("calcLine").innerHTML = "weighing need, access gap and deployment cost";
    const seen = new Set(), top = [];
    for (const p of result.pairs) {
      if (!seen.has(p.hotspot.id)) { seen.add(p.hotspot.id); top.push(p.hotspot); }
      if (top.length === 3) break;
    }
    for (const h of top) {
      fxLayer.addLayer(L.polyline([[s.lat, s.lon], [h.lat, h.lon]], {
        color: "#d55181", weight: 2, opacity: 0.85, className: "short-line", interactive: false,
      }));
    }
  }, SCAN_MS);

  /* lock: draw the winning route, light up the pair, show the result */
  setTimeout(() => {
    if (!live()) return;
    $("calcTitle").textContent = "DISPATCH LOCKED";
    $("calcLine").innerHTML =
      `${agShort(best.agency)} &rarr; pickup &rarr; ${best.hotspot.location}`;
    $("calcCount").textContent = fmtInt(result.evaluated);

    /* keep only radar + winning graphics */
    fxLayer.eachLayer(l => { if (l.options.className === "short-line") fxLayer.removeLayer(l); });

    const a = best.agency, h = best.hotspot;
    fxLayer.addLayer(L.polyline([[a.lat, a.lon], [s.lat, s.lon]], {
      color: "#3987e5", weight: 2.5, opacity: 0.85, className: "route-leg1", interactive: false,
    }));
    fxLayer.addLayer(L.polyline([[s.lat, s.lon], [h.lat, h.lon]], {
      color: "#1baf7a", weight: 3.5, opacity: 0.95, className: "route-leg2", interactive: false,
    }));
    $("ag-" + a.id).classList.add("winner");
    const hEl = hotspotMarkers[h.id].getElement();
    if (hEl) hEl.classList.add("hs-winner");

    map.flyToBounds(L.latLngBounds([[a.lat, a.lon], [s.lat, s.lon], [h.lat, h.lon]]).pad(0.18), { duration: 0.8 });

    renderResult(s, result);
    setTimeout(() => { if (live()) $("calcOverlay").classList.remove("show"); }, 2600);
  }, SCAN_MS + SHORTLIST_MS);
}

/* ---------------------------------------------------------- result panel */
function renderResult(s, result) {
  const b = result.pairs[0];
  const h = b.hotspot, a = b.agency;
  const boostPct = Math.round((b.boost - 1) * 100);
  const fmv = s.report.lbs * C.FMV_PER_LB;

  /* alternates: next best pairs with a distinct agency or hotspot */
  const alts = [];
  for (const p of result.pairs.slice(1)) {
    if (alts.length === 3) break;
    if (p.agency !== a || p.hotspot !== h) alts.push(p);
  }

  $("resultBody").innerHTML = `
    <div class="rb-eyebrow">Dispatch recommendation</div>
    <div class="rb-source">from <b>${s.name}</b> &middot; ${s.report.lbs} lbs ${s.surplus}
      &middot; ${fmtInt(result.meals)} meals &middot; reported ${s.report.time}</div>

    <div class="pair">
      <div class="pair-node pn-agency">
        <div class="pn-badge">${TRUCK_SVG.replace("<svg", '<svg width="17" height="17"')}</div>
        <div>
          <div class="pn-role">Collecting agency</div>
          <div class="pn-name">${a.name}</div>
          <div class="pn-sub">${a.program}</div>
        </div>
      </div>
      <div class="pair-arrow"></div>
      <div class="pair-node pn-pickup">
        <div class="pn-badge">${typeIcon[s.type] || "🍽"}</div>
        <div>
          <div class="pn-role">Pickup</div>
          <div class="pn-name">${s.name}</div>
          <div class="pn-sub">${s.report.items}</div>
        </div>
      </div>
      <div class="pair-arrow"></div>
      <div class="pair-node pn-hotspot">
        <div class="pn-badge">📍</div>
        <div>
          <div class="pn-role">Distribution hotspot</div>
          <div class="pn-name">${h.location} &middot; ${h.area}</div>
          <div class="pn-sub">need ${h.need.toFixed(1)} &middot; rank #${h.rank} of 382
            &middot; food access ${h.accessDays.toFixed(h.accessDays % 1 ? 1 : 0)} d/wk</div>
        </div>
      </div>
    </div>

    <div class="outcomes">
      <div class="oc oc-people"><div class="v" data-count="${b.served}">0</div><div class="k">people fed</div></div>
      <div class="oc"><div class="v" data-count="${b.miles}" data-dec="1">0</div><div class="k">route miles</div></div>
      <div class="oc oc-net ${b.net < 0 ? "neg" : ""}"><div class="v" data-count="${b.net}" data-money="1">0</div><div class="k">net benefit</div></div>
    </div>

    <div class="score-viz">
      <div class="sv-row sv-reward"><span class="sv-label">Reward</span>
        <span class="sv-track"><span class="sv-fill" data-w="${b.reward}"></span></span>
        <span class="sv-val">${fmt$(b.reward)}</span></div>
      <div class="sv-row sv-cost"><span class="sv-label">Op. cost</span>
        <span class="sv-track"><span class="sv-fill" data-w="${b.cost}"></span></span>
        <span class="sv-val">&minus;${fmt$(b.cost).slice(1)}</span></div>
      <div class="sv-row sv-net"><span class="sv-label">Net</span>
        <span class="sv-track"><span class="sv-fill" data-w="${Math.max(b.net, 0)}"></span></span>
        <span class="sv-val">${fmt$(b.net)}</span></div>
    </div>

    ${result.prepared ? `<div class="rb-note">🍛 <b>Prepared food</b> — only agencies that accept
      prepared meals were considered (${result.eligible.length} of ${AGENCIES.length}).</div>` : ""}
    ${boostPct > 0 ? `<div class="rb-note">⚡ <b>Access-gap boost +${boostPct}%</b> — this block has
      scheduled food access only ${h.accessDays.toFixed(h.accessDays % 1 ? 1 : 0)} days/week, so its
      reward is weighted up.</div>` : ""}
    ${b.surplus >= 1 ? `<div class="rb-note">📦 Block need absorbs ${fmtInt(b.served)} meals;
      remaining <b>${fmtInt(b.surplus)} meals</b> ride along to ${a.name.split(" (")[0]}&rsquo;s
      pantry network.</div>` : ""}
    <div class="rb-note tax">🧾 Donation logged for <b>${s.name}</b> — est. deductible fair market
      value <b>${fmt$(fmv)}</b> (${s.report.lbs} lbs &times; $${C.FMV_PER_LB}/lb).</div>

    <table class="rb-table">
      <tr><td>HQ &rarr; pickup &rarr; hotspot</td><td>${b.leg1.toFixed(1)} + ${b.leg2.toFixed(1)} mi</td></tr>
      <tr><td>Drive + handling time</td><td>${fmtInt(b.driveMin)} + ${C.HANDLING_MIN} min</td></tr>
      <tr><td>Personnel ($${C.WAGE_PER_HR}/hr)</td><td>${fmt$(b.labor)}</td></tr>
      <tr><td>Vehicle ($${C.COST_PER_MILE}/mi)</td><td>${fmt$(b.mileage)}</td></tr>
      <tr class="total"><td>Deployment cost</td><td>${fmt$(b.cost)}</td></tr>
    </table>

    <div class="rb-h">Runners-up (${fmtInt(result.evaluated)} pairs evaluated)</div>
    ${alts.map((p, i) => `
      <div class="alt-row"><span class="alt-rank">${i + 2}.</span>
        <span class="alt-pair"><b>${agShort(p.agency)}</b>
          &rarr; ${p.hotspot.location}</span>
        <span class="alt-net">${fmt$(p.net)}</span></div>`).join("")}

    <details class="model">
      <summary>How this was scored — the reward&#8209;cost model</summary>
      <div class="model-body"><em>net = reward − cost</em>
reward = min(meals, need) × $${C.MEAL_VALUE}/meal × accessBoost
         + overflow meals × $${C.MEAL_VALUE} × 0.5 (pantry)
accessBoost = 1 + ${C.ACCESS_BOOST_MAX} × (7 − access days/wk)/7
cost = (drive + ${C.HANDLING_MIN} min) × $${C.WAGE_PER_HR}/hr        [SD min. wage 2026]
       + road miles × $${C.COST_PER_MILE}/mi              [IRS rate 2026]
meals = lbs ÷ ${C.LBS_PER_MEAL}                        [Feeding America]
distances: haversine × ${C.ROAD_FACTOR} at ${C.AVG_SPEED_MPH} mph city speed</div>
    </details>`;

  $("resultBody").hidden = false;

  /* count-up + bar-grow animations */
  const maxBar = Math.max(b.reward, b.cost, 1);
  requestAnimationFrame(() => {
    document.querySelectorAll(".sv-fill").forEach(el => {
      el.style.width = (parseFloat(el.dataset.w) / maxBar * 100) + "%";
    });
  });
  document.querySelectorAll("#resultBody .v[data-count]").forEach(el => {
    const target = parseFloat(el.dataset.count);
    const money = el.dataset.money, dec = el.dataset.dec ? 1 : 0;
    const start = performance.now();
    (function step(now) {
      const p = Math.min((now - start) / 900, 1);
      const v = target * (1 - Math.pow(1 - p, 3));
      el.textContent = money ? fmt$(v) : v.toFixed(dec ? 1 : 0);
      if (p < 1) requestAnimationFrame(step);
    })(start);
  });
}
