/* BellyUp demo — voluntary surplus reports in, collector→hotspot dispatch out,
   confirmed deliveries recorded to the ledger (receipts + serving limits).
   Data comes from data.js (generated by scripts/build_demo_data.py). */

"use strict";

const C = CONSTANTS;
const CANDIDATES = HOTSPOTS.filter(h => h.need >= C.MIN_CANDIDATE_NEED);
const REPORTING = SUPPLIERS.filter(s => s.report);

/* Collectors = agency trucks + mobile pantry units whose schedule has staff
   on site tonight. Capacity is what separates them: a pantry van handles the
   long tail nearby; an agency box truck handles bulk. */
const COLLECTORS = [
  ...AGENCIES.map(a => ({ ...a, kind: "agency", capacityLbs: C.AGENCY_CAPACITY_LBS })),
  ...PANTRIES.filter(p => p.dispatchable).map(p => ({ ...p, kind: "pantry", capacityLbs: C.PANTRY_CAPACITY_LBS })),
];

/* ---------------------------------------------------------------- helpers */
const $ = id => document.getElementById(id);
const fmt$ = v => (v < 0 ? "-$" : "$") + Math.abs(v).toFixed(2);
const fmtInt = v => Math.round(v).toLocaleString();
const agShort = a => a.name
  .replace("Jacobs & Cushman San Diego Food Bank", "SD Food Bank")
  .replace("Catholic Charities Diocese of San Diego", "Catholic Charities")
  .replace("Stepping Higher Incorporated", "Stepping Higher");

function haversineMi(a, b) {
  const R = 3958.76, rad = Math.PI / 180;
  const dLat = (b.lat - a.lat) * rad, dLon = (b.lon - a.lon) * rad;
  const s = Math.sin(dLat / 2) ** 2 +
    Math.cos(a.lat * rad) * Math.cos(b.lat * rad) * Math.sin(dLon / 2) ** 2;
  return 2 * R * Math.asin(Math.sqrt(s));
}
const roadMi = (a, b) => haversineMi(a, b) * C.ROAD_FACTOR;

/* ------------------------------------------------------------------ theme */
/* Light is the default. The choice persists per browser. Map geometry reads
   the --c-* tokens so both themes drive colors from styles.css. */
const TILE_URLS = {
  light: "https://{s}.basemaps.cartocdn.com/light_all/{z}/{x}/{y}{r}.png",
  dark: "https://{s}.basemaps.cartocdn.com/dark_all/{z}/{x}/{y}{r}.png",
};
let theme = "light";
try { theme = localStorage.getItem("bellyup.theme") || "light"; } catch (e) { /* private mode */ }
applyThemeAttr();

function applyThemeAttr() {
  if (theme === "dark") document.documentElement.setAttribute("data-theme", "dark");
  else document.documentElement.removeAttribute("data-theme");
}
function themeColor(token) {
  return getComputedStyle(document.documentElement).getPropertyValue(token).trim();
}

/* ----------------------------------------------------------------- ledger */
/* HISTORY (from data.js) = past days, read-only. Tonight's confirmed
   deliveries live in localStorage and drive the serving limits. */
const LS_KEY = "bellyup.deliveries." + C.DEMO_DATE;
let tonight = [];
try { tonight = JSON.parse(localStorage.getItem(LS_KEY) || "[]"); } catch (e) { tonight = []; }

function saveTonight() {
  try { localStorage.setItem(LS_KEY, JSON.stringify(tonight)); } catch (e) { /* best effort */ }
}
const dispatchedSupplierIds = () => new Set(tonight.map(r => r.supplierId));
const servedMealsTonight = hid =>
  tonight.filter(r => r.hotspotId === hid).reduce((t, r) => t + r.servedMeals, 0);
const dropsTonight = hid => tonight.filter(r => r.hotspotId === hid).length;
function hotspotClosed(h) {
  if (h.need < C.MIN_CANDIDATE_NEED) return false;  // never in the pool
  return dropsTonight(h.id) >= C.MAX_DROPS_PER_NIGHT ||
    h.need - servedMealsTonight(h.id) < 1;
}

/* ------------------------------------------------------- matching engine */
/* Input: one supplier report. Output: ranked (collector, hotspot) pairs.
   Serving limit: a hotspot already at MAX_DROPS_PER_NIGHT deliveries, or with
   its need already met tonight, leaves the candidate pool; partially served
   blocks only count their REMAINING need. So the same block is never piled on.
   net = reward − cost
   reward = mealsServed × MEAL_VALUE × accessBoost + surplusMeals × MEAL_VALUE × 0.5
     collected    = min(lbs reported, collector capacity)
     mealsServed  = min(collected meals, remaining need) — one meal per person
     accessBoost  = 1 + ACCESS_BOOST_MAX × (7 − food-access days/wk)/7
     surplus      = collected meals beyond remaining need — agency pantry
                    network, or the pantry site's next scheduled distribution
   cost = labor + mileage over base → pickup → hotspot
     labor    = (drive minutes + handling) × $17.75/hr
     mileage  = road miles × $0.76/mi                                        */
function computeDispatch(supplier) {
  const lbs = supplier.report.lbs;
  const meals = lbs / C.LBS_PER_MEAL;
  const prepared = supplier.surplus === "prepared";
  const eligible = COLLECTORS.filter(c => !prepared || c.acceptsPrepared);
  const open = CANDIDATES.filter(h => !hotspotClosed(h));
  const pairs = [];

  for (const col of eligible) {
    const leg1 = roadMi(col, supplier);
    const collectedLbs = Math.min(lbs, col.capacityLbs);
    const uncollectedLbs = lbs - collectedLbs;
    const colMeals = collectedLbs / C.LBS_PER_MEAL;
    for (const h of open) {
      const remaining = h.need - servedMealsTonight(h.id);
      const leg2 = roadMi(supplier, h);
      const miles = leg1 + leg2;
      const driveMin = miles / C.AVG_SPEED_MPH * 60;
      const minutes = driveMin + C.HANDLING_MIN;
      const labor = minutes / 60 * C.WAGE_PER_HR;
      const mileage = miles * C.COST_PER_MILE;

      const served = Math.min(colMeals, remaining);
      const surplus = colMeals - served;
      const boost = 1 + C.ACCESS_BOOST_MAX * (7 - Math.min(h.accessDays, 7)) / 7;
      const reward = served * C.MEAL_VALUE * boost + surplus * C.MEAL_VALUE * 0.5;

      pairs.push({
        collector: col, hotspot: h,
        collectedLbs, uncollectedLbs, remaining,
        leg1, leg2, miles, driveMin, minutes, labor, mileage,
        cost: labor + mileage,
        served, surplus, boost, reward,
        net: reward - (labor + mileage),
      });
    }
  }
  pairs.sort((p, q) => q.net - p.net);
  return { meals, prepared, eligible, openCount: open.length, pairs, evaluated: pairs.length };
}

/* ------------------------------------------------------------------- map */
const map = L.map("map", { zoomControl: true, attributionControl: true });
const tiles = L.tileLayer(TILE_URLS[theme], {
  attribution: '&copy; <a href="https://www.openstreetmap.org/copyright">OSM</a> &copy; <a href="https://carto.com/">CARTO</a>',
  maxZoom: 19,
}).addTo(map);

const downtown = L.latLngBounds(HOTSPOTS.map(h => [h.lat, h.lon]));
map.fitBounds(downtown.pad(0.12));

const fxLayer = L.layerGroup().addTo(map);   // scan lines, routes, radar

/* hotspot circles — magenta, sized by need; aqua once served/at limit */
const hotspotMarkers = {};
function hotspotStyle(h) {
  const closed = hotspotClosed(h);
  const col = closed ? themeColor("--c-route") : themeColor("--c-hotspot");
  return {
    radius: 3 + Math.sqrt(h.need) * 2.1,
    color: col,
    weight: 1.4,
    opacity: closed ? 0.9 : 0.8,
    fillColor: col,
    fillOpacity: closed ? 0.3 : 0.16 + Math.min(h.need / 40, 0.34),
  };
}
function hotspotTip(h) {
  const servedNow = servedMealsTonight(h.id);
  const status = hotspotClosed(h)
    ? `<br><b style="color:${themeColor("--c-route")}">served tonight — off the candidate list</b>`
    : servedNow > 0 ? `<br>${fmtInt(servedNow)} meals delivered tonight; ${(h.need - servedNow).toFixed(1)} need remaining` : "";
  return `<b>${h.location}</b> &middot; ${h.area}` +
    `<div class="tip-k">need ${h.need.toFixed(1)} person-equivalents &middot; rank #${h.rank}` +
    `<br>food access ${h.accessDays.toFixed(h.accessDays % 1 ? 1 : 0)} days/week${status}</div>`;
}
for (const h of HOTSPOTS) {
  const m = L.circleMarker([h.lat, h.lon], { ...hotspotStyle(h), className: "hs-path" }).addTo(map);
  m.bindTooltip(hotspotTip(h), { className: "hs-tip", direction: "top", opacity: 1 });
  hotspotMarkers[h.id] = m;
}
function refreshHotspots() {
  for (const h of HOTSPOTS) {
    hotspotMarkers[h.id].setStyle(hotspotStyle(h));
    hotspotMarkers[h.id].setTooltipContent(hotspotTip(h));
  }
}

/* agency HQ markers */
const TRUCK_SVG = '<svg viewBox="0 0 24 24" fill="currentColor"><path d="M3 5h11v9H3zM14 8h4l3 3v3h-7zM6 18a2 2 0 1 0 0-4 2 2 0 0 0 0 4zm11 0a2 2 0 1 0 0-4 2 2 0 0 0 0 4z"/></svg>';
for (const a of AGENCIES) {
  L.marker([a.lat, a.lon], {
    icon: L.divIcon({ className: "", html: `<div class="mk-agency" id="col-${a.id}">${TRUCK_SVG}</div>`, iconSize: [26, 26], iconAnchor: [13, 13] }),
    zIndexOffset: 500,
  }).addTo(map).bindTooltip(
    `<b>${a.name}</b><div class="tip-k">${a.program}` +
    `<br>${a.acceptsPrepared ? "accepts prepared food" : "packaged/produce"}</div>`,
    { className: "hs-tip", direction: "top", opacity: 1 }
  );
}

/* mobile pantry sites — violet diamonds; solid = unit available tonight */
for (const p of PANTRIES) {
  const cls = p.dispatchable ? "mk-pantry" : "mk-pantry idle";
  const status = p.dispatchable
    ? '<br><b class="tip-pantry">mobile unit available tonight</b>'
    : `<br>${p.whyNot}`;
  L.marker([p.lat, p.lon], {
    icon: L.divIcon({ className: "", html: `<div class="${cls}" id="col-${p.id}"></div>`, iconSize: [16, 16], iconAnchor: [8, 8] }),
    zIndexOffset: 400,
  }).addTo(map).bindTooltip(
    `<b>${p.name}</b><div class="tip-k">${p.operator} &middot; ${p.program}` +
    `<br>runs ${p.schedule}${status}</div>`,
    { className: "hs-tip", direction: "top", opacity: 1 }
  );
}

/* supplier markers — the "input markers", always on the map */
for (const s of SUPPLIERS) {
  const cls = s.report ? "mk-supplier" : "mk-supplier quiet";
  const m = L.marker([s.lat, s.lon], {
    icon: L.divIcon({ className: "", html: `<div class="${cls}" id="sp-${s.id}"></div>`, iconSize: [14, 14], iconAnchor: [7, 7] }),
    zIndexOffset: 700,
  }).addTo(map);
  const rep = s.report
    ? `<br><b class="tip-supplier">${s.report.lbs} lbs</b> ${s.surplus} &middot; reported ${s.report.time}`
    : "<br>no surplus reported tonight";
  m.bindTooltip(
    `<b>${s.name}</b><div class="tip-k">${s.type}${rep}</div>`,
    { className: "hs-tip", direction: "top", opacity: 1 }
  );
  if (s.report) m.on("click", () => {
    if (dispatchedSupplierIds().has(s.id)) openLedger(); else selectReport(s);
  });
}

/* ------------------------------------------------------------------ feed */
const typeIcon = { grocery: "🛒", hotel: "🏨", venue: "🏟", health: "🏥" };
function renderFeed() {
  const done = dispatchedSupplierIds();
  $("feed").innerHTML = REPORTING.map(s => {
    const rec = tonight.find(r => r.supplierId === s.id);
    return `
    <div class="report-card ${done.has(s.id) ? "done" : ""}" id="card-${s.id}">
      <div class="rc-top">
        <span>${typeIcon[s.type] || "🍽"}</span>
        <span class="rc-name">${s.name}</span>
        <span class="rc-time">${s.report.time}</span>
      </div>
      <div class="rc-mid">
        <span class="rc-lbs">${s.report.lbs} lbs</span>
        <span class="rc-meals">&asymp; ${fmtInt(s.report.lbs / C.LBS_PER_MEAL)} meals</span>
        <span class="rc-chip ${s.surplus === "prepared" ? "prepared" : ""}">${s.surplus}</span>
      </div>
      <div class="rc-items">${s.report.items}</div>
      ${rec ? `<div class="rc-done">✓ dispatched &middot; ${agShort({ name: rec.collector })} &rarr; ${rec.hotspot}</div>` : ""}
    </div>`;
  }).join("");
  for (const s of REPORTING) {
    $("card-" + s.id).addEventListener("click", () => {
      if (dispatchedSupplierIds().has(s.id)) openLedger(); else selectReport(s);
    });
  }
  for (const s of REPORTING) {
    const el = $("sp-" + s.id);
    if (el) el.classList.toggle("dispatched", done.has(s.id));
  }
}

/* --------------------------------------------------------------- topbar */
function renderStats() {
  const totLbs = REPORTING.reduce((t, s) => t + s.report.lbs, 0);
  const fed = tonight.reduce((t, r) => t + r.servedMeals, 0);
  $("topstats").innerHTML = [
    [fmtInt(totLbs) + " lbs", "reported tonight"],
    ["~" + fmtInt(totLbs / C.LBS_PER_MEAL), "potential meals"],
    [REPORTING.length - tonight.length, "pending reports"],
    [fmtInt(fed), "people fed tonight"],
  ].map(([v, k]) => `<div class="stat-chip"><div class="v">${v}</div><div class="k">${k}</div></div>`).join("");
  $("ledgerCount").textContent = tonight.length;
}
$("topdate").textContent = new Date().toLocaleDateString("en-US",
  { weekday: "short", month: "short", day: "numeric", year: "numeric" });

/* ------------------------------------------------- selection + animation */
let animToken = 0;
let selectedId = null;
let currentMatch = null;   // { supplier, result } for the confirm button

function clearFx() {
  fxLayer.clearLayers();
  $("calcOverlay").classList.remove("show");
  document.querySelectorAll(".mk-agency.winner, .mk-pantry.winner").forEach(el => el.classList.remove("winner"));
  document.querySelectorAll(".mk-supplier.selected").forEach(el => el.classList.remove("selected"));
  for (const id in hotspotMarkers) {
    const el = hotspotMarkers[id].getElement();
    if (el) el.classList.remove("hs-winner", "hs-scanned");
  }
}

function selectReport(s) {
  if (selectedId === s.id) return;
  selectedId = s.id;
  const token = ++animToken;
  clearFx();

  document.querySelectorAll(".report-card.active").forEach(el => el.classList.remove("active"));
  const card = $("card-" + s.id);
  card.classList.add("active");
  card.scrollIntoView({ block: "nearest", behavior: "smooth" });
  $("sp-" + s.id).classList.add("selected");

  const result = computeDispatch(s);
  currentMatch = { supplier: s, result };
  runTriangulation(s, result, token);
}

function runTriangulation(s, result, token) {
  const best = result.pairs[0];
  const live = () => token === animToken;

  /* hide any previous result while we "compute" */
  $("resultBody").hidden = true;
  $("resultEmpty").style.display = "none";

  const scanBounds = L.latLngBounds(HOTSPOTS.map(h => [h.lat, h.lon])).extend([s.lat, s.lon]);
  map.flyToBounds(scanBounds.pad(0.1), { duration: 0.55 });

  /* radar pulse at the supplier */
  fxLayer.addLayer(L.marker([s.lat, s.lon], {
    icon: L.divIcon({ className: "", html: '<div class="radar"><span></span><span></span><span></span></div>', iconSize: [12, 12], iconAnchor: [6, 6] }),
    interactive: false, zIndexOffset: 900,
  }));

  /* calc overlay */
  const constraint = result.prepared
    ? `constraint: prepared food &rarr; ${result.eligible.length} of ${COLLECTORS.length} collectors eligible`
    : `${result.eligible.length} collectors &times; ${result.openCount} open blocks`;
  $("calcTitle").textContent = "TRIANGULATING";
  $("calcLine").innerHTML = `${s.name} &middot; ${constraint}`;
  $("calcOverlay").classList.add("show");

  const SCAN_MS = 1350, SHORTLIST_MS = 850;

  /* pair counter counts up through the scan */
  const t0 = performance.now();
  (function tick(now) {
    if (!live()) return;
    const p = Math.min((now - t0) / SCAN_MS, 1);
    $("calcCount").textContent = fmtInt(result.evaluated * (1 - Math.pow(1 - p, 3)));
    if (p < 1) requestAnimationFrame(tick);
  })(t0);

  /* scan lines: quick flicks from the supplier to sampled candidate blocks */
  const openIds = new Set(result.pairs.map(p => p.hotspot.id));
  const sample = CANDIDATES.filter(h => openIds.has(h.id)).sort(() => Math.random() - 0.5).slice(0, 26);
  sample.forEach((h, i) => {
    setTimeout(() => {
      if (!live()) return;
      const line = L.polyline([[s.lat, s.lon], [h.lat, h.lon]], {
        color: themeColor("--c-supplier"), weight: 1.3, opacity: 0.9,
        className: "scan-line", interactive: false,
      });
      fxLayer.addLayer(line);
      setTimeout(() => fxLayer.removeLayer(line), 520);
      const el = hotspotMarkers[h.id].getElement();
      if (el) { el.classList.remove("hs-scanned"); void el.getBBox; el.classList.add("hs-scanned"); }
    }, 90 + i * (SCAN_MS - 200) / sample.length);
  });

  /* shortlist: top-3 hotspots pulse while collectors are weighed */
  setTimeout(() => {
    if (!live()) return;
    $("calcTitle").textContent = "SHORTLISTING";
    $("calcLine").innerHTML = "weighing need, access gap, serving limits and deployment cost";
    const seen = new Set(), top = [];
    for (const p of result.pairs) {
      if (!seen.has(p.hotspot.id)) { seen.add(p.hotspot.id); top.push(p.hotspot); }
      if (top.length === 3) break;
    }
    for (const h of top) {
      fxLayer.addLayer(L.polyline([[s.lat, s.lon], [h.lat, h.lon]], {
        color: themeColor("--c-hotspot"), weight: 2, opacity: 0.85,
        className: "short-line", interactive: false,
      }));
    }
  }, SCAN_MS);

  /* lock: draw the winning route, light up the pair, show the result */
  setTimeout(() => {
    if (!live()) return;
    $("calcTitle").textContent = "DISPATCH LOCKED";
    $("calcLine").innerHTML =
      `${agShort(best.collector)} &rarr; pickup &rarr; ${best.hotspot.location}`;
    $("calcCount").textContent = fmtInt(result.evaluated);

    /* keep only radar + winning graphics */
    fxLayer.eachLayer(l => { if (l.options.className === "short-line") fxLayer.removeLayer(l); });

    const a = best.collector, h = best.hotspot;
    fxLayer.addLayer(L.polyline([[a.lat, a.lon], [s.lat, s.lon]], {
      color: themeColor(a.kind === "pantry" ? "--c-pantry" : "--c-agency"),
      bellyRole: a.kind === "pantry" ? "--c-pantry" : "--c-agency",
      weight: 2.5, opacity: 0.85, className: "route-leg1", interactive: false,
    }));
    fxLayer.addLayer(L.polyline([[s.lat, s.lon], [h.lat, h.lon]], {
      color: themeColor("--c-route"), bellyRole: "--c-route",
      weight: 3.5, opacity: 0.95, className: "route-leg2", interactive: false,
    }));
    $("col-" + a.id).classList.add("winner");
    const hEl = hotspotMarkers[h.id].getElement();
    if (hEl) hEl.classList.add("hs-winner");

    map.flyToBounds(L.latLngBounds([[a.lat, a.lon], [s.lat, s.lon], [h.lat, h.lon]]).pad(0.18), { duration: 0.8 });

    renderResult(s, result);
    setTimeout(() => { if (live()) $("calcOverlay").classList.remove("show"); }, 2600);
  }, SCAN_MS + SHORTLIST_MS);
}

/* ---------------------------------------------------------- result panel */
function renderResult(s, result) {
  const b = result.pairs[0];
  const h = b.hotspot, a = b.collector;
  const isPantry = a.kind === "pantry";
  const boostPct = Math.round((b.boost - 1) * 100);
  const fmv = s.report.lbs * C.FMV_PER_LB;
  const servedBefore = servedMealsTonight(h.id);

  /* alternates: next best pairs with a distinct collector or hotspot */
  const alts = [];
  for (const p of result.pairs.slice(1)) {
    if (alts.length === 3) break;
    if (p.collector !== a || p.hotspot !== h) alts.push(p);
  }

  $("resultBody").innerHTML = `
    <div class="rb-eyebrow">Dispatch recommendation</div>
    <div class="rb-source">from <b>${s.name}</b> &middot; ${s.report.lbs} lbs ${s.surplus}
      &middot; ${fmtInt(result.meals)} meals &middot; reported ${s.report.time}</div>

    <div class="pair">
      <div class="pair-node ${isPantry ? "pn-pantryunit" : "pn-agency"}">
        <div class="pn-badge">${TRUCK_SVG.replace("<svg", '<svg width="17" height="17"')}</div>
        <div>
          <div class="pn-role">${isPantry ? "Mobile pantry unit" : "Collecting agency"}</div>
          <div class="pn-name">${a.name}</div>
          <div class="pn-sub">${isPantry ? `${a.operator} &middot; ${a.program}` : a.program}</div>
        </div>
      </div>
      <div class="pair-arrow"></div>
      <div class="pair-node pn-pickup">
        <div class="pn-badge">${typeIcon[s.type] || "🍽"}</div>
        <div>
          <div class="pn-role">Pickup</div>
          <div class="pn-name">${s.name}</div>
          <div class="pn-sub">${s.report.items}</div>
        </div>
      </div>
      <div class="pair-arrow"></div>
      <div class="pair-node pn-hotspot">
        <div class="pn-badge">📍</div>
        <div>
          <div class="pn-role">Distribution hotspot</div>
          <div class="pn-name">${h.location} &middot; ${h.area}</div>
          <div class="pn-sub">need ${h.need.toFixed(1)} &middot; rank #${h.rank} of 382
            &middot; food access ${h.accessDays.toFixed(h.accessDays % 1 ? 1 : 0)} d/wk${
              servedBefore > 0 ? ` &middot; ${fmtInt(servedBefore)} meals already tonight` : ""}</div>
        </div>
      </div>
    </div>

    <div class="outcomes">
      <div class="oc oc-people"><div class="v" data-count="${b.served}">0</div><div class="k">people fed</div></div>
      <div class="oc"><div class="v" data-count="${b.miles}" data-dec="1">0</div><div class="k">route miles</div></div>
      <div class="oc oc-net ${b.net < 0 ? "neg" : ""}"><div class="v" data-count="${b.net}" data-money="1">0</div><div class="k">net benefit</div></div>
    </div>

    <div class="score-viz">
      <div class="sv-row sv-reward"><span class="sv-label">Reward</span>
        <span class="sv-track"><span class="sv-fill" data-w="${b.reward}"></span></span>
        <span class="sv-val">${fmt$(b.reward)}</span></div>
      <div class="sv-row sv-cost"><span class="sv-label">Op. cost</span>
        <span class="sv-track"><span class="sv-fill" data-w="${b.cost}"></span></span>
        <span class="sv-val">&minus;${fmt$(b.cost).slice(1)}</span></div>
      <div class="sv-row sv-net"><span class="sv-label">Net</span>
        <span class="sv-track"><span class="sv-fill" data-w="${Math.max(b.net, 0)}"></span></span>
        <span class="sv-val">${fmt$(b.net)}</span></div>
    </div>

    <button class="btn-confirm" id="confirmBtn">✓ Confirm dispatch &amp; log receipt</button>

    ${result.prepared ? `<div class="rb-note">🍛 <b>Prepared food</b> — only collectors that accept
      prepared meals were considered (${result.eligible.length} of ${COLLECTORS.length}).</div>` : ""}
    ${servedBefore > 0 ? `<div class="rb-note">🎯 <b>Serving limit</b> — this block already received
      ${fmtInt(servedBefore)} meals tonight; only its remaining need of ${b.remaining.toFixed(1)}
      counts toward the reward.</div>` : ""}
    ${boostPct > 0 ? `<div class="rb-note">⚡ <b>Access-gap boost +${boostPct}%</b> — this block has
      scheduled food access only ${h.accessDays.toFixed(h.accessDays % 1 ? 1 : 0)} days/week, so its
      reward is weighted up.</div>` : ""}
    ${b.uncollectedLbs >= 1 ? `<div class="rb-note">🚐 <b>Unit capacity ${a.capacityLbs} lbs</b> —
      the pantry van collects ${fmtInt(b.collectedLbs)} lbs; ${fmtInt(b.uncollectedLbs)} lbs stay
      with the donor for a second pickup.</div>` : ""}
    ${b.surplus >= 1 ? `<div class="rb-note">📦 Block need absorbs ${fmtInt(b.served)} meals;
      remaining <b>${fmtInt(b.surplus)} meals</b> ${isPantry
        ? `stock ${agShort(a)}&rsquo;s next scheduled distribution`
        : `ride along to ${agShort(a)}&rsquo;s pantry network`}.</div>` : ""}
    <div class="rb-note tax">🧾 Confirming logs a receipt for <b>${s.name}</b> — est. deductible
      fair market value <b>${fmt$(fmv)}</b> (${s.report.lbs} lbs &times; $${C.FMV_PER_LB}/lb).</div>

    <table class="rb-table">
      <tr><td>${isPantry ? "Site" : "HQ"} &rarr; pickup &rarr; hotspot</td><td>${b.leg1.toFixed(1)} + ${b.leg2.toFixed(1)} mi</td></tr>
      <tr><td>Drive + handling time</td><td>${fmtInt(b.driveMin)} + ${C.HANDLING_MIN} min</td></tr>
      <tr><td>Personnel ($${C.WAGE_PER_HR}/hr)</td><td>${fmt$(b.labor)}</td></tr>
      <tr><td>Vehicle ($${C.COST_PER_MILE}/mi)</td><td>${fmt$(b.mileage)}</td></tr>
      <tr class="total"><td>Deployment cost</td><td>${fmt$(b.cost)}</td></tr>
    </table>

    <div class="rb-h">Runners-up (${fmtInt(result.evaluated)} pairs evaluated)</div>
    ${alts.map((p, i) => `
      <div class="alt-row"><span class="alt-rank">${i + 2}.</span>
        <span class="alt-pair"><b>${p.collector.kind === "pantry" ? "🚐 " : ""}${agShort(p.collector)}</b>
          &rarr; ${p.hotspot.location}</span>
        <span class="alt-net">${fmt$(p.net)}</span></div>`).join("")}

    <details class="model">
      <summary>How this was scored — the reward&#8209;cost model</summary>
      <div class="model-body"><em>net = reward − cost</em>
collectors = agency trucks (${C.AGENCY_CAPACITY_LBS} lb) + pantry
  units on site tonight (${C.PANTRY_CAPACITY_LBS} lb van)
serving limit = ${C.MAX_DROPS_PER_NIGHT} deliveries/hotspot/night; served
  blocks leave the pool, partial blocks count remaining need
reward = min(collected meals, remaining need) × $${C.MEAL_VALUE}/meal × accessBoost
         + overflow meals × $${C.MEAL_VALUE} × 0.5 (pantry)
accessBoost = 1 + ${C.ACCESS_BOOST_MAX} × (7 − access days/wk)/7
cost = (drive + ${C.HANDLING_MIN} min) × $${C.WAGE_PER_HR}/hr        [SD min. wage 2026]
       + road miles × $${C.COST_PER_MILE}/mi              [IRS rate 2026]
meals = lbs ÷ ${C.LBS_PER_MEAL}                        [Feeding America]
distances: haversine × ${C.ROAD_FACTOR} at ${C.AVG_SPEED_MPH} mph city speed</div>
    </details>`;

  $("resultBody").hidden = false;
  $("confirmBtn").addEventListener("click", confirmDispatch);

  /* count-up + bar-grow animations */
  const maxBar = Math.max(b.reward, b.cost, 1);
  requestAnimationFrame(() => {
    document.querySelectorAll(".sv-fill").forEach(el => {
      el.style.width = (parseFloat(el.dataset.w) / maxBar * 100) + "%";
    });
  });
  document.querySelectorAll("#resultBody .v[data-count]").forEach(el => {
    const target = parseFloat(el.dataset.count);
    const money = el.dataset.money, dec = el.dataset.dec ? 1 : 0;
    const start = performance.now();
    (function step(now) {
      const p = Math.min((now - start) / 900, 1);
      const v = target * (1 - Math.pow(1 - p, 3));
      el.textContent = money ? fmt$(v) : v.toFixed(dec ? 1 : 0);
      if (p < 1) requestAnimationFrame(step);
    })(start);
  });
}

/* ------------------------------------------------------------ confirming */
function confirmDispatch() {
  if (!currentMatch) return;
  const { supplier: s, result } = currentMatch;
  if (dispatchedSupplierIds().has(s.id)) return;
  const b = result.pairs[0];

  const now = new Date();
  tonight.push({
    receipt: `BU-${C.DEMO_DATE.replaceAll("-", "")}-T${String(tonight.length + 1).padStart(2, "0")}`,
    date: C.DEMO_DATE,
    time: now.getHours().toString().padStart(2, "0") + ":" + now.getMinutes().toString().padStart(2, "0"),
    supplierId: s.id, supplier: s.name,
    lbs: s.report.lbs, collectedLbs: Math.round(b.collectedLbs),
    servedMeals: Math.round(b.served), surplusMeals: Math.round(b.surplus),
    collector: b.collector.name, kind: b.collector.kind,
    hotspotId: b.hotspot.id, hotspot: b.hotspot.location,
    fmv: Math.round(s.report.lbs * C.FMV_PER_LB * 100) / 100,
    net: Math.round(b.net * 100) / 100,
  });
  saveTonight();

  refreshHotspots();
  renderFeed();
  renderStats();

  const btn = $("confirmBtn");
  btn.outerHTML = `<div class="confirmed-note">✓ Dispatched — receipt ${tonight[tonight.length - 1].receipt} logged
    <div class="cn-sub">${b.hotspot.location} ${hotspotClosed(b.hotspot)
      ? "is now fully served tonight and leaves the candidate pool"
      : `has ${(b.hotspot.need - servedMealsTonight(b.hotspot.id)).toFixed(1)} need remaining tonight`}</div></div>`;
}

/* ---------------------------------------------------------------- ledger */
function renderLedger() {
  const all = [...tonight].reverse().map(r => ({ ...r, isTonight: true }))
    .concat([...HISTORY].reverse());
  const grand = [...HISTORY, ...tonight];

  const totalLbs = grand.reduce((t, r) => t + r.lbs, 0);
  const totalFmv = grand.reduce((t, r) => t + r.fmv, 0);
  const totalFed = grand.reduce((t, r) => t + r.servedMeals, 0);
  $("ledgerTiles").innerHTML = [
    [fmtInt(grand.length), "deliveries logged", ""],
    [fmtInt(tonight.length), "tonight", "lt-route"],
    [fmtInt(totalLbs) + " lbs", "food recovered", ""],
    [fmtInt(totalFed), "people fed", "lt-route"],
    ["$" + fmtInt(totalFmv), "est. FMV deductions", "lt-good"],
  ].map(([v, k, cls]) => `<div class="lt ${cls}"><div class="v">${v}</div><div class="k">${k}</div></div>`).join("");

  $("ledgerLog").innerHTML = all.length ? all.map(r => `
    <div class="receipt ${r.isTonight ? "tonight" : ""}">
      <div class="rt-top">
        <span class="rt-id">${r.receipt}</span>
        ${r.isTonight ? '<span class="rt-badge">tonight</span>' : ""}
        <span class="rt-when">${r.date} &middot; ${r.time}</span>
      </div>
      <div class="rt-flow"><b>${r.supplier}</b> <span class="rt-arrow">&rarr;</span>
        ${r.kind === "pantry" ? "🚐" : "🚚"} ${agShort({ name: r.collector })}
        <span class="rt-arrow">&rarr;</span> 📍 ${r.hotspot}</div>
      <div class="rt-nums">
        <span><b>${r.lbs}</b> lbs donated</span>
        <span><b>${r.servedMeals}</b> people fed</span>
        <span class="fmv">est. FMV <b>${fmt$(r.fmv)}</b></span>
        <span>net ${fmt$(r.net)}</span>
      </div>
    </div>`).join("") : '<div class="served-empty">No deliveries logged yet.</div>';

  /* donor tax summary */
  const byDonor = {};
  for (const r of grand) {
    (byDonor[r.supplier] ||= { n: 0, lbs: 0, fmv: 0 });
    byDonor[r.supplier].n++; byDonor[r.supplier].lbs += r.lbs; byDonor[r.supplier].fmv += r.fmv;
  }
  const donors = Object.entries(byDonor).sort((a, b) => b[1].fmv - a[1].fmv);
  $("ledgerDonors").innerHTML = `
    <table class="donor-table">
      <tr><th>Donor</th><th>Deliveries</th><th>Lbs</th><th>Est. FMV</th></tr>
      ${donors.map(([name, d]) => `
        <tr><td>${name}</td><td>${d.n}</td><td>${fmtInt(d.lbs)}</td>
        <td class="fmv">${fmt$(d.fmv)}</td></tr>`).join("")}
    </table>`;

  /* hotspots served tonight */
  $("limitLabel").textContent = C.MAX_DROPS_PER_NIGHT;
  const servedIds = [...new Set(tonight.map(r => r.hotspotId))];
  $("ledgerServed").innerHTML = servedIds.length ? servedIds.map(hid => {
    const h = HOTSPOTS.find(x => x.id === hid);
    const meals = servedMealsTonight(hid), drops = dropsTonight(hid);
    const closed = hotspotClosed(h);
    return `
    <div class="served-row">
      <div class="sr-top">
        <span class="sr-loc">${h.location}</span>
        ${closed ? '<span class="sr-limit">at limit</span>' : ""}
        <span class="sr-stat">${fmtInt(meals)}/${h.need.toFixed(0)} meals &middot; ${drops}/${C.MAX_DROPS_PER_NIGHT} drops</span>
      </div>
      <div class="sr-bar"><span style="width:${Math.min(meals / h.need * 100, 100)}%"></span></div>
    </div>`;
  }).join("") : '<div class="served-empty">Nothing served yet tonight — every block is still in the pool.</div>';
}

function openLedger() { renderLedger(); $("ledger").hidden = false; }
$("ledgerBtn").addEventListener("click", openLedger);
$("ledgerClose").addEventListener("click", () => { $("ledger").hidden = true; });
$("ledger").addEventListener("click", e => { if (e.target === $("ledger")) $("ledger").hidden = true; });
$("resetBtn").addEventListener("click", () => {
  tonight = [];
  saveTonight();
  location.reload();
});

/* ----------------------------------------------------------- theme toggle */
function setThemeButton() {
  $("themeBtn").textContent = theme === "dark" ? "☀️" : "🌙";
  $("themeBtn").title = theme === "dark" ? "Switch to light mode" : "Switch to dark mode";
}
$("themeBtn").addEventListener("click", () => {
  theme = theme === "dark" ? "light" : "dark";
  try { localStorage.setItem("bellyup.theme", theme); } catch (e) { /* best effort */ }
  applyThemeAttr();
  setThemeButton();
  tiles.setUrl(TILE_URLS[theme]);
  refreshHotspots();
  fxLayer.eachLayer(l => {
    if (l.options.bellyRole && l.setStyle) l.setStyle({ color: themeColor(l.options.bellyRole) });
  });
});

/* ------------------------------------------------------------------- boot */
setThemeButton();
renderFeed();
renderStats();
refreshHotspots();
